name: test

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  
env:
  DEPLOY_PATH: x
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Pull
          id: pull
          run: |
            docker pull dslim/slim
            docker pull nginx:latest
          shell: bash
        - name: Run
          id: run
          run: |
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim build nginx:latest
#docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/slim build nginx:latest
          shell: bash
        - name: Ps
          id: ps
          run: |
            docker ps -a
          shell: bash
        - name: Images
          id: images
          run: |
            docker images
          shell: bash
        